
version: '3.3'

services:
  ffmt_loki:
    image: grafana/loki:main
    container_name: ${LOKI_CONTAINER_NAME}
    restart: "unless-stopped"
    command: 
      "-config.expand-env=true -config.file=/etc/loki/loki-config.yml"
    environment:
      - LOKI_HOST_HTTP_PORT=${LOKI_HOST_HTTP_PORT}
      - LOKI_HOST_GRPC_PORT=${LOKI_HOST_GRPC_PORT}
    ports:
      - ${LOKI_HOST_HTTP_PORT}:3100
      - ${LOKI_HOST_GRPC_PORT}:9095
    volumes:
      - ./docker/loki/:/etc/loki
    networks:
      - ffmt_network
  
  ffmt_promtail:
    image: grafana/promtail:main
    container_name: ${PROMTAIL_CONTAINER_NAME}
    restart: "unless-stopped"
    command: "-config.expand-env=true -config.file=/etc/promtail/promtail-config.yml"
    ports:
      - ${PROMTAIL_HOST_PORT}:9080
    environment:
      - LOKI_HOST_HTTP_PORT=${LOKI_HOST_HTTP_PORT}
    volumes:
      - ${FFMT_BACKEND_LOGS_DIR}:/var/log/backend
      - ${FFMT_REDIS_ACTION_LOGS_DIR}:/var/log/redis/action
      - ${FFMT_REDIS_ERROR_LOGS_DIR}:/var/log/redis/error
      - ${FFMT_REDIS_DEBUG_LOGS_DIR}:/var/log/redis/debug
      - ./docker/promtail:/etc/promtail
    networks:
      - ffmt_network

  ffmt_grafana:
    image: grafana/grafana-oss:latest
    container_name: ${GRAFANA_CONTAINER_NAME}
    user: "0:0"
    restart: "unless-stopped"
    environment:
      - GF_SERVER_PROTOCOL=https
      - GF_SERVER_CERT_FILE=${GRAFANA_SSL_CERT}
      - GF_SERVER_CERT_KEY=${GRAFANA_SSL_PRIVATE_KEY}
    ports:
      - ${GRAFANA_HOST_PORT}:3000
    volumes:
      - ${HOST_SSL_CERTS_DIR}:${GRAFANA_SSL_CERTS_DIR}
      - ${HOST_SSL_PRIVATE_KEY_DIR}:${GRAFANA_SSL_PRIVATE_KEY_DIR}
      - ./docker/grafana/data:/var/lib/grafana
    networks:
      - ffmt_network

  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: "no"
    ports:
      - ${PORTAINER_HOST_PORT}:9000
      - ${PORTAINER_HOST_SSL_PORT}:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker/portainer/data:/data
      - ${HOST_SSL_CERT}:/certs/portainer.cert
      - ${HOST_SSL_PRIVATE_KEY}:/certs/portainer.key
    command:
      --sslcert /certs/portainer.cert
      --sslkey /certs/portainer.key
    networks:
      - ffmt_network

  ffmt_prometheus:
    image: prom/prometheus:latest
    container_name: ${PROMETHEUS_CONTAINER_NAME}
    restart: "unless-stopped"
    command: "--config.file=/etc/prometheus/prometheus-config.yml"
    user: "0:0"
    volumes:
      - ./docker/prometheus/etc/prometheus:/etc/prometheus
      - ./docker/prometheus/prometheus:/prometheus
    networks:
      - ffmt_network



######## PROMETHEUS EXPORTERS ########
  ffmt_node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: ${NODE_EXPORTER_CONTAINER_NAME}
    command:
     - '--path.rootfs=/host'
    pid: host
    restart: unless-stopped
    volumes:
     - '/:/host:ro,rslave'
    networks:
     - ffmt_network
  
  ffmt_cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: ${CADVISOR_CONTAINER_NAME}
    volumes:
     - /:/rootfs:ro
     - /var/run:/var/run:ro
     - /sys:/sys:ro
     - /var/lib/docker:/var/lib/docker:ro
     - /dev/disk/:/dev/disk:ro
    devices:
     - /dev/kmsg
    networks:
      - ffmt_network

networks:
  ffmt_network:
    driver: bridge